### ISSUE TITLE
'item 1'

### ISSUE THREAD

**Issue by Khalelyk** [GekidoLukas/weaponleveling#10]
latest version of the mod: 1.18.2-1.3.jar
break many types of blocks including saplings and tinker tables(part table, crafting station, tool station), mod gives players separate item "item1 *.*" (Ex. "item1 oak_sapling") that has a red background, and is an unlimited sapling item, can only be removed from inventory by placing red background item in a chest

**Comment by GekidoLukas** [comment]
Will be fixed in the next Version
