### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by WardsParadox** [GekidoLukas/weaponleveling#12]
**Describe the bug**
Was unsure if this is a dup of #9 due to them reporting (assumingly forge) issues. I don't have the Fabric Config API Port installed (maybe in another mod), so I assume it's this one (gladly wrong there). Adding a newer version of the fabirc config api port next to the mod fixes it.

Additionally, creating a brand new instance, with just Fabric installed, creates the same error. 

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.3.1- FABRIC

**To Reproduce**
Launch, immediate error at launch

**Expected behavior**
No failures launching

**Screenshots**
N/A

**Additional context**

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Forge Config API Port' (forgeconfigapiport) 3.2.0 with version 3.2.4 or later.
Unmet dependency listing:
	 - Mod 'Weapon Leveling' (weaponleveling) fabric-1.18.2-1.3.1 requires version 3.2.4 or later of mod 'Forge Config API Port' (forgeconfigapiport), but only the wrong version is present: 3.2.0!

**Comment by GekidoLukas** [comment]
Hello, I am not sure what the issue currently is. Sorry if I understood anything wrong here. The Fabric Version of Weapon Leveling requires the latest Forge Config Api Version 3.2.4. It seems you have installed an older one.
Please tell me if I am wrong, but the issue just seems to be, that you require version 3.2.4, and then it works.

**Comment by WardsParadox** [comment]
If I install the mod, it crashes at start stating 3.2.0 of Forge Config is installed, but it requires 3.2.4 despite not being installed at all.

Is Forge Config API Port built into Fabric now?

**Comment by GekidoLukas** [comment]
Okay, I am a bit confused. 
When you install my mod, it crashes with the Forge Config API mod?
If the config API's version is lower than 3.2.4, it is supposed to crash, because it requires the mod at that version.

Could you give me the exact mod list of it crashing and of it working, please?

**Comment by WardsParadox** [comment]
Install new instance of Minecraft.
Install Fabric, Fabric Loader.
Install Weapon Leveling only.

Error:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
- Replace mod 'Forge Config API Port' (forgeconfigapiport) 3.2.0 with version 3.2.4 or later.
Unmet dependency listing:
- Mod 'Weapon Leveling' (weaponleveling) fabric-1.18.2-1.3.1 requires version 3.2.4 or later of mod 'Forge Config API Port' (forgeconfigapiport), but only the wrong version is present: 3.2.0!

**Comment by WardsParadox** [comment]
same setup, now adding the latest Forge Config API Port, 3.2.4

no error, no crash.

**Comment by GekidoLukas** [comment]
The crashing is expected behavior. The Forge Config API Port mod is required on the Fabric Version.
Though, I am not quite sure, why it thinks there is a Version on your client already.
I will take a look at it, though I did not change that many parts to make a dependency. 🤔

**Comment by WardsParadox** [comment]
Interesting indeed! Well glad to know expected crash is expected haha. Closing
