### ISSUE TITLE
[Crash]Incompatible with debugify.

### ISSUE THREAD

**Issue by 6371peter** [GekidoLukas/weaponleveling#13]
**Describe the bug**
Incompatible with debugify.

**Mod/Minecraft Version**
Forge Version:1.18.2-40.1.80
Mod Version:
weaponleveling-1.18.2-1.3.4
debugify-1.11.0-forge-1.18.2
cloth-config-6.2.62-forge

**To Reproduce**
1. Download weaponleveling and debugify and cloth-config
2. Use HMCL run the game(java version:jdk-18.0.1.1)
3. Then game crash

**Additional context**
HMCL exported logs:[https://pastebin.com/aRJZShWw](https://pastebin.com/aRJZShWw)

**Comment by GekidoLukas** [comment]
Debugify seems to cause the issue, since they also use MixinExtras and seem to not relocate it. I talked to the author of MixinExtras and this is likely the cause. I don't know if Debugify's author still works on 1.18, but this is probably an issue on their side
