### ISSUE TITLE
Item stacking problem caused by NBT tag

### ISSUE THREAD

**Issue by Elaski6573** [GekidoLukas/weaponleveling#14]
**Describe the bug**
Problem with NBT tag
Item which used in my hand got nbt tag named tag :{}

**Mod/Minecraft Version**
Minecraft Version: Forge 1.18.2-40.1.80
Mod Version:1.3.4, 1.3.3 (tested with two verserons)

**To Reproduce**
1. Mine block with item (example = dirt, acacia log)
2. Item which used to mine got a NBT tag named tag: {}
3. This item NEVER get stacked with other items

I noticed this problem by using command /data get entity @p Inventory

**Expected behavior**
1. Fix nbt tag to not apply to common items
2. Or change that only durable items can get nbt tag

**Screenshots**
![화면 캡처 2022-10-06 084631](https://user-images.githubusercontent.com/114150904/194198773-02c47f54-dd0c-4e8f-b5cb-8253fe4ad756.png)

**Comment by GekidoLukas** [comment]
Oh, I see why this might happen. I will look into this, thank you!

**Comment by Dr-WeiAL** [comment]
I also had this problem today, which caused my items to not stack and caused problems using Storage Drawers

**Comment by GeradesoLukas** [comment]
Hey, so I will probably be able to fix this in the next update, but a quick fix I found is that you can double-click when hovering with an item over the same type of item and then everything will have the NBT `tag:{}` removed from it

**Comment by CCCClear** [comment]
I had the same problem and came looking for a solution, and it looks like someone saw it before I did. 
Hope to get a hot fix soon. It doesn't crash, but it detracts from the experience. 
My OCD makes it impossible for me to ignore this little bug.

**Comment by GekidoLukas** [comment]
The Fix already works in my testing. I will finish up some things and the next update will contain it
