### ISSUE TITLE
(Forge-1.18.2) Cannot invoke "net.minecraft.world.entity.player.Player.m_7500_()" because the return value of "net.minecraftforge.event.world.BlockEvent$BlockToolModificationEvent.getPlayer()" is null

### ISSUE THREAD

**Issue by PhweeDev** [GekidoLukas/weaponleveling#15]
Easily one of the weirdest bugs I've seen so far. I tried to right click a flower with **bone **meal**** (to get more flowers, I believe a mod adds that feature, it might be vanilla, idk) and then my game crashes. This is on 1.18.2 Forge, latest version. Below is the log and report. (Note: it could possibly be ShetiPhanCore)

Log: https://paste.gg/p/anonymous/31933ecbd2224ee688a4449fc1fc9eac

Report:  https://paste.gg/p/anonymous/9f3b4752f0bf4b2d84b699cc1fc52595

**Comment by PhweeDev** [comment]
I can confirm this is an incompatibility with ShetiPhianCore and Weapon Leveling 1.3.4/3/2/1. But not on 1.2.3.

**Comment by GekidoLukas** [comment]
I will look at making ShetiphianCore compatible, thanks for the report

**Comment by PhweeDev** [comment]
Anytime. hopefully it's a quick fix and you can get it out soon. I can't play the mod atm because of that.

**Comment by GekidoLukas** [comment]
Will be fixed in the next update
