### ISSUE TITLE
[Suggestion] Crayfish Gun Mod compatibility

### ISSUE THREAD

**Issue by craigprime** [GekidoLukas/weaponleveling#16]
**Describe your Suggestion**
The weapons added by CGM don't receive the bonus damage when leveling. I'd love to see a patch if possible. Absolutely loving the mod!

Thanks!

**Comment by GekidoLukas** [comment]
Huh, interesting, I usually have a fallback system for guns. I will take a look at it.

**Comment by GekidoLukas** [comment]
Dedicated Support will be added in the next Version
