### ISSUE TITLE
Items won't stack properly

### ISSUE THREAD

**Issue by Khalelyk** [GekidoLukas/weaponleveling#18]
**Describe the bug**
Items when gathered will form mulitple stacks of unmergeable items (ie: saplings, logs, flowers, sugar cane etc) 

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.3.4

**To Reproduce**
1. Play as usual
2. Collect logs, saplings, etc
3. notice that items stack weird, 2 separate stacks of 1-3 items, that cannot be merged

**Expected behavior**
Items to stack as usual

**Screenshots**
n/a

**Additional context**
n/a

**Comment by GekidoLukas** [comment]
Duplicate of #14 - Will be fixed in the upcoming update
