### ISSUE TITLE
Incompatible with Tetra

### ISSUE THREAD

**Issue by Elaski6573** [GekidoLukas/weaponleveling#19]
**Describe the bug**
It makes that seems all of durability of item is removed but actually this item is not broken.
When I move or use this item, durability has been returned.

This bug happens with Tetra item which is usable(or throwable) with right click.
Usually occours with tomahawk, throwing knife, and spear(lightweight handle)
Bug doesn't happens at creative.

Bows and Shields and vanilla items has no problem.

+
Also you can reproduce this bug by using mod Epic Fight.
This mod gives a skill Active Guard that defend enemy's melee or projectile attack.
You can use tetra/modular_sword to defend by right click but after this behavior, durability is removed

**Mod/Minecraft Version**
Minecraft Version:Forge 1.18.2-40.1.80
Mod Version:
Weapon Leveling 1.3.4
Tetra 1.18.2-4.10.1
Art of Forging(Addon) 1.5.4 <-- Actually this is similar to datapack
mutil 4.5.0

**To Reproduce**
1. Usually this bug is reproduced with throwable items.
2. Use this item with short right click
3. Text has been came out "This is the item1 *NAME*" and 
    it seems that all of duability has been removed and also you can't use this item
 - (Client thinks it doesn't have a duability but server thinks it has duability)
 - (You can repair this bug by attacking enemy or mining block and move item inside your inventory)

**Expected behavior**
N/A

**Screenshots**
![Tetra weaonleveling error](https://user-images.githubusercontent.com/114150904/196836674-996b6070-2078-4f84-9ff8-25910912ccc0.gif)

**Additional context**
There seems to be a big problem with the right click.
Right click and durability disappearing problem produces item copying bug.
This two bugs looks very similar and only causes in survival mod only a situation in which durability may be lost.

**Comment by GekidoLukas** [comment]
Hey, I fixed a similar issue for a mod called `Parry This!`. I will soon release a dev build on my Discord Server, it would be great if you can test, if the issue still applies

**Comment by Elaski6573** [comment]
I tested with dev version.
All of bugs have fixed! Thanks!
