### ISSUE TITLE
Weapons not doing any damage in my modpack

### ISSUE THREAD

**Issue by DrBLOOD95** [GekidoLukas/weaponleveling#2]
**Describe the bug**

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version:weaponleveling-1.18.2-1.1

I am playing with a modpack over 200 mods, your mod worked fine when I tested it alone but adding it in my modpack made it so my weapons weren't doing any damage at all.

I am sending you a random crash report so you can see all the installed mods

[crash-2022-08-01_20.01.35-client.txt](https://github.com/GeradesoLukas/weaponleveling/files/9237414/crash-2022-08-01_20.01.35-client.txt)
.

**Comment by GekidoLukas** [comment]
I will look into this and see what mod could cause the issue

**Comment by GekidoLukas** [comment]
Okay, so I looked into this and neither Golden Age Combat nor Offhand Combat seem to be incompatible.

I would recommend using a binary search for testing what mod could cause it (removing half of the other mods and seeing if it works and if it does look keep searching the half that doesn't)

Unfortunately, it is too much work to download every modpack people find incompatibilities in. I can only help if I know the specific mod

**Comment by DrBLOOD95** [comment]
Alright I'll do my investigation

**Comment by DrBLOOD95** [comment]
Alright after further investigations it seems that the bug doesnt come from any other mod at all but from changing the config files! here are mine, and it's not w
[weaponleveling-server.txt](https://github.com/GeradesoLukas/weaponleveling/files/9261525/weaponleveling-server.txt)
orking at all

**Comment by GekidoLukas** [comment]
Fixed in Version 1.2
