### ISSUE TITLE
[Suggestion]More Comprehensive Client Config

### ISSUE THREAD

**Issue by CCCClear** [GekidoLukas/weaponleveling#20]
I am a modpack maker and I think this mod is very simple and useful.
Recently I met problems in adjusting my modpack, I want to put the contents of the server config in the client config.
This way, after I give the modpack to players, they can also enjoy the full config in the new world. 
But now the server config needs to modify in the saves, this increased complexity.
If you can provide a solution?

**Comment by GekidoLukas** [comment]
Hello, I am a modpack maker myself, so I know this kind of issue.
The serverconfig can be put in a folder called defaultconfigs. These will be taken as the default for every new save. If you want to update the files in the saves, there is a great mod called [serverconfig updater](https://www.curseforge.com/minecraft/mc-mods/serverconfig-updater)

You can't however put contents in the client config. I need to use the server config for easy communication between server and client.

There would also be the new data pack based system you could use. Keep in mind, this would also require a global data pack loader mod.

**Comment by CCCClear** [comment]
Thank you for your reply. I learned a lot from it. 
I will try the method you introduced, and then I will close the issue.
