### ISSUE TITLE
[Crash] Incompatibility with Parry This!

### ISSUE THREAD

**Issue by Kutomi1** [GekidoLukas/weaponleveling#21]
With the newest version, the game crashes when trying to start it with both this mod and [Parry This!](https://www.curseforge.com/minecraft/mc-mods/parrying) installed. Older versions work fine.

Minecraft Version: 1.18.2
Mod Version: 1.4.0

**To Reproduce**
1. Install Weapon Leveling 1.4.0 and Parry This!
2. Start the game

**Comment by GeradesoLukas** [comment]
Could you provide me with a crash report, please?

**Comment by GekidoLukas** [comment]
It is actually a similar issue to something I had before. I tried it myself, and it should be fixed in the next Update.

**Comment by Kutomi1** [comment]
Thanks!
