### ISSUE TITLE
Unable to start the game

### ISSUE THREAD

**Issue by Dr-WeiAL** [GekidoLukas/weaponleveling#24]
**Describe the bug**
Unable to start the game

**Mod/Minecraft Version**
Minecraft Version:1.18.2 forge
Mod Version:1.4.2

**Expected behavior**
Start the game

**Additional context**
[latest.log](https://github.com/GeradesoLukas/weaponleveling/files/9944906/latest.log)

**Comment by pepedota7** [comment]
Quite similar. Same version. [latest.log](https://github.com/GeradesoLukas/weaponleveling/files/9945128/latest.log)
Mods list if needed. [mods.txt](https://github.com/GeradesoLukas/weaponleveling/files/9945135/mods.txt)

**Comment by GekidoLukas** [comment]
Oh this might be related to a fix I did on the fabric version. This has likely to do with better combat, but I am not sure why it happens just now.

**Comment by GekidoLukas** [comment]
The latest Version on curseforge should have a fix for that. Could you please check?

**Comment by Dr-WeiAL** [comment]
> The latest Version on curseforge should have a fix for that. Could you please check?

This version can start the game normally, incidentally I found that the projectile_items is missing a cgm:rifle, and then tetra compatibility is missing tetra:modular_single
（tetra:modular_single can be a trident）

**Comment by pepedota7** [comment]
Can confirm on my end. The game start and works as it should. Thank you very much for the fix.

**Comment by GekidoLukas** [comment]
> > The latest Version on curseforge should have a fix for that. Could you please check?
> 
> This version can start the game normally, incidentally I found that the projectile_items is missing a cgm:rifle, and then tetra compatibility is missing tetra:modular_single （tetra:modular_single can be a trident）

Is added and will be uploaded with the next update ^^
