### ISSUE TITLE
[1.18.2] Server Crash When Player Shot By Twilight Forest Slime Beetle

### ISSUE THREAD

**Issue by MokahTGS** [GekidoLukas/weaponleveling#26]
**Describe the bug**
We are seeing a consistent server crash when a player is shot by a Twilight Forest slime beetle projectile while wearing broken vanilla armor.  

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: weaponleveling-1.18.2-1.4.1.jar

**To Reproduce**
1. Go to Twilight Forest
2. Get shot by slime beetle
3. Server crashes
4. Crash Log: https://pastebin.com/mW8uJ5GG

This is for the Cosmic Magitech modpack: https://www.curseforge.com/minecraft/modpacks/cosmic-magitech

**Comment by GekidoLukas** [comment]
I tested this with the latest Version and there is no crash. I consider this fixed for now.
