### ISSUE TITLE
[Suggestion]Tetra single modular tools need leveling

### ISSUE THREAD

**Issue by Elaski6573** [GekidoLukas/weaponleveling#27]
**Describe your Suggestion**
Since there are a lot of weapon types.
Vanilla weapons, sword, bow, axe, and trident has own specialized combat style.
Also, Tetra has many kinds of weapons. But some of weapons doesn't get leveling progress.

Tetra single modular tools can't get leveling progress as same as Vanilla shovel.
But single modular tool have weapon type : spear
This is big problem to spear users. If I change handle modular to lightweight handle, then it is throwable and works same as trident.
Tetra supports to change modular of trident but changing modular makes trident impossible to gain leveling progress.

I know that usually shovel doesn't used as weapon but this makes impossible to gain leveling progress for single modular tools.

**Comment by GekidoLukas** [comment]
Hello, I already added tetra:modular_single in the development version, and it works. I will release this as the last version before the rework, so this will be fixed.
