### ISSUE TITLE
Incompatible with epic fight

### ISSUE THREAD

**Issue by SeanChengN** [GekidoLukas/weaponleveling#3]
**Describe the bug**
When used at the same time with epic fight, the weapon damage is wrong.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: weaponleveling-1.18.2-1.2

**To Reproduce**
![explorer_DxmnviYpIx](https://user-images.githubusercontent.com/20624068/187828792-541c11e1-e0b6-49e0-86a6-591a82a3c08b.png)
Just use both

**Expected behavior**
Damage should be correct

**Screenshots**
![2022-09-01_11 55 46](https://user-images.githubusercontent.com/20624068/187828543-9c06e29a-4954-41c7-99a1-27cdcf83bb5b.png)

**Additional context**

**Comment by GekidoLukas** [comment]
This should be fixed with the 2.0 Update. It will be released soon. Thanks for the report
