### ISSUE TITLE
Incompatable With EndRemastered

### ISSUE THREAD

**Issue by Elaski6573** [GekidoLukas/weaponleveling#30]
**Describe the bug**
When you place the eye on end portal frame, then Eye brokes.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2-40.1.84
Mod Version: Weaponleveling-1.18.2-1.4.3
                      EndRem 5.2.0-R-1.18.2

**To Reproduce**
Just place the endrem eye on portal frame.

**Screenshots**
![image](https://user-images.githubusercontent.com/114150904/207035180-03b55225-7dd2-44db-a131-e2ac91ed8300.png)

**Additional context**
Not a serious problem. But it seems to be fixed.

**Comment by GekidoLukas** [comment]
I will remove this feature in the upcoming Update and make it a separate mod

**Comment by GekidoLukas** [comment]
This is still a feature in the current mod and should now be fixed
