### ISSUE TITLE
Incompatable with Aquaculture

### ISSUE THREAD

**Issue by Elaski6573** [GekidoLukas/weaponleveling#31]
**Describe the bug**
Neptunium fillet knife is always broken
Neptunium fillet knife has "blank" nbt

**Mod/Minecraft Version**
Minecraft Version: 1.18.2-40.1.84
Mod Version : Weaponleveling-1.18.2-1.4.3
Aquaculture-1.18.2-2.4.1

**To Reproduce**
none

**Screenshots**
![image](https://user-images.githubusercontent.com/114150904/209036352-b54f2728-6a94-48c6-9a51-4d7f52630100.png)
![image](https://user-images.githubusercontent.com/114150904/209037366-6548266d-0d4c-4e85-a602-784d489ae6f2.png)

**Additional context**
https://github.com/TeamMetallurgy/Aquaculture/issues/377

**Comment by GekidoLukas** [comment]
This should be fixed in 2.0
