### ISSUE TITLE
Incompatible with Epic Knights: Shields, Armor and Weapons by magistu_

### ISSUE THREAD

**Issue by PandaMcBoomBoom** [GekidoLukas/weaponleveling#32]
**Describe the bug**
Game won't launch if these two are installed with each other.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.3

**To Reproduce**
1. Install Weapon Leveling and Epic Knights: Shields, Armor and Weapons together
2. Launch Game
3. Exit Code 1, check latest.log, and stops at loading in Epic Knights: Shields, Armor and Weapons

**Expected behavior**
For the game to launch with both mods installed.

**Screenshots**
I don't have any shots of it, but can if absolutely needed I guess.

**Additional context**
Works with every other mod I have installed, game would launch with "Epic Knights: Shields, Armor and Weapons" but I remove that mod and it works perfectly fine.

**Comment by GekidoLukas** [comment]
Probably same issue as #46. Will close in favor of #46 having more info.
