### ISSUE TITLE
Incompatibility between 'Valkyrien Skies' and 'Weapon Leveling'

### ISSUE THREAD

**Issue by ghost** [GekidoLukas/weaponleveling#34]
**Description of the bug:**

Seems like the mod isn't compatible with the 'Valkyrien Skies' mod. The game doesn't even launch and throws an 'Exit code: 1'.
The mod also needs 'Kotlin for Forge' to work, so I ran minecraft with only kotlin and 'Weapon Leveling' mod and minecraft started just fine. 'Valkyrien Skies' also starts ok without 'Weapon Leveling'.

**Mod/Minecraft Version:**

Minecraft Version: 1.18.2
Mod Version: weaponleveling-1.18.2-1.4.3

**Steps to reproduce the behavior:**
1. download and place into mods folder; 'Valkyrien Skies' mod version '[Forge 1.18.2] v2.1.0-beta9'.
2. download and place into mods folder; 'Kotlin for Forge' mod version 'Kotlin for Forge 3.9.1'.
3. download and place into mods folder; 'weaponleveling-1.18.2-1.4.3'.
4. run minecraft with Forge version 'release 1.18.2-forge-40.2.0'.
5. game crashes with 'Exit Code: 1'.

**Comment by GekidoLukas** [comment]
Not enough info here, but I assume this is the same as #46, so I will close this in favor of #46 having more info.
