### ISSUE TITLE
[Suggestion] Compatibility with Epic Fight

### ISSUE THREAD

**Issue by Smoker120900** [GekidoLukas/weaponleveling#38]
My weapons won't gain exp while using Epic Fight's combat animations system, can you make a compat patch for WL to work with Epic Fight??

**Comment by GekidoLukas** [comment]
I will check if Epic Fight is compatible with the upcoming 2.0 Update. If yes, this will be marked as closed

**Comment by Smoker120900** [comment]
it is now with the latest Epic Fight Update, but i have another question, will you update this mod to 1.20.1??

**Comment by GekidoLukas** [comment]
Yeah, I made a dedicated support for Epic Fight Mod including the Offhand. This will be in the next update for 1.18.2

1.20.1 will come eventually, but I will make 1.19 version(s) first
