### ISSUE TITLE
It keeps telling me to remove mod but no telling me why?

### ISSUE THREAD

**Issue by Sunsetgaming** [GekidoLukas/weaponleveling#39]
**Describe the bug**
I just says <html>Remove mod 'Weapon Leveling' (weaponleveling) fabric-1.18.2-1.3.1<br>(C:\Users\jondoe\AppData\Roaming\.minecraft\mods\weaponleveling-fabric-1.18.2-1.3.1.jar).</html>
**Mod/Minecraft Version**
Minraft Version: 1.18.2
Mod Version:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by GekidoLukas** [comment]
I need more information to do this. But a likely cause is that the mod "Forge Config API Port" is not installed
