### ISSUE TITLE
Curse of Binding and soulbound block slot

### ISSUE THREAD

**Issue by MURUMokay** [GekidoLukas/weaponleveling#40]
**Describe the bug**
Broken thing with curse of Binding and soulbound from Ensorcellation gets unusable and blocks slot.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.3

**To Reproduce**
1. Get item with curse of Binding and soulbound
2. Broke it to full unusable
3. Try to take it off
4. See issue

**Expected behavior**
I thought, item will go to inventory or fall off, but it's not.

**Screenshots**

![IMG_20230702_125417](https://github.com/GeradesoLukas/weaponleveling/asot/88540054/e8838bcc-63f8-45ac-999f-b982091d59a7)

**Comment by GekidoLukas** [comment]
Ah, thank you I will add a mechanic to remove the item in the upcoming update
