### ISSUE TITLE
Supremium items can't be used.

### ISSUE THREAD

**Issue by Ipnotisen** [GekidoLukas/weaponleveling#44]
**Describe the bug**
Any Supremium items from Mystical Aggriculture seems broken and can't be used.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.3

**To Reproduce**
Craft any Supremium item.

**Expected behavior**
Usable.

**Screenshots**
![image](https://github.com/GeradesoLukas/weaponleveling/assets/72452447/15ae0790-1c72-4fb1-8898-594330388964)

**Comment by GekidoLukas** [comment]
Should be fixed in 2.0
