### ISSUE TITLE
1.18.2 Startup crash with Respiteful

### ISSUE THREAD

**Issue by xFirefalconx** [GekidoLukas/weaponleveling#45]
**Describe the bug**
Crashes on startup with exit code 1

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.3
Respiteful 1.1.2b

**To Reproduce**
1. Enable Weapon Leveling, Respiteful and all dependencies
2. Try to launch - does it crash? Welcome to my situation.
3. Disable Respiteful but keep dependencies on,
4. Try to launch again, does it launch? Great, same situation for me.

**Expected behavior**
Game launches with Respiteful on.

**Screenshots**
![grafik](https://github.com/GeradesoLukas/weaponleveling/assets/106652912/bc37265a-a94c-4d6e-9871-7743fa622278)

**Additional context**
Tested within my modpack and with the above shown setup
Have no idea which of the two mods causes the crash so uh... hope you can do anything about this or maybe give some info from what you find. 

[2023-10-06-1.log](https://github.com/GeradesoLukas/weaponleveling/files/12833345/2023-10-06-1.log)
[latest.log](https://github.com/GeradesoLukas/weaponleveling/files/12833336/latest.log)

**Comment by GekidoLukas** [comment]
Same issue as #46. Will close in favor of less issues.
