### ISSUE TITLE
Startup crash with latest ModernFix versions (unfixable on their end)

### ISSUE THREAD

**Issue by xFirefalconx** [GekidoLukas/weaponleveling#46]
**Describe the bug**
Game crashes on startup.

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.3
Modernfix 5.7.0+

**To Reproduce**
Install both mods

**Expected behavior**
No crash

**Screenshots**
N/A

**Additional context**
embeddedt states that your mod is using the mixin library wrong. Maybe this is also the reason why so many other mods crash?
https://github.com/embeddedt/ModernFix/issues/226
https://github.com/embeddedt/ModernFix/issues/257

**Comment by GekidoLukas** [comment]
Thank you for the information. I am currently investigating if this issue still occurs in my 2.0 Update. Otherwise, I will mark it as closed once it is released on curseforge and modrinth

**Comment by MindSetFPS** [comment]
Still having this error on 1.21 mohist server
