### ISSUE TITLE
crash mod use magma

### ISSUE THREAD

**Issue by joaoespanhol** [GekidoLukas/weaponleveling#48]
Step:
1º put mod 
2º put magma
3º start magma.

Logs: debug: https://mclo.gs/pCW9VRz 
LastLog: https://mclo.gs/Ng8BpY5 
console: https://mclo.gs/6WOzdFw

**Comment by TonimatasDEV** [comment]
> Step: 1º put mod 2º put magma 3º start magma.
> 
> Logs: debug: https://mclo.gs/pCW9VRz LastLog: https://mclo.gs/Ng8BpY5 console: https://mclo.gs/6WOzdFw

This is a magma crash, close it
