### ISSUE TITLE
BowItem and CrossbowItem Compatibility

### ISSUE THREAD

**Issue by Hyomoto** [GekidoLukas/weaponleveling#55]
I apologize if this is a needless report, I didn't do full verification here but after noticing the way bows are defined in the configs and that these two aren't mentioned, it would improve mod compatibility across the board if weapon compatibility for bows and crossbows were inherited from that class instead.  So, in the event that the config is being used to define a bow and crossbow on a case-by-case basis, I would like to suggest expanding detection to these classes for the given reason.

**Comment by GekidoLukas** [comment]
Hello, that is a good point, I will see if I can change that. I do use those classes, but add them later. I may actually add them via the class too

**Comment by GekidoLukas** [comment]
I looked at the code and this is already a feature I added. A class they both inherit which is the "ProjectileWeaponItem" Class. Any class inheriting BowItem or CrossbowItem should also count
