### ISSUE TITLE
Compat for CGM fork on 1.20.1

### ISSUE THREAD

**Issue by HollowScourgeM** [GekidoLukas/weaponleveling#57]
Hi, there is an unofficial fork for MrCrayfish's Gun Mod for 1.20.1, the link is here [https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod-unofficial](url)
I've been trying to get it to work through the configs (on 1.20.1) but nothing seems to be working and I can't figure it out, can you make the mod compatible with this fork please? 
If you don't have the time it's totally understandable and it'd be cool to have an example datapack for peeps like me to try and make (I don't know jack about datapack-making)

**Comment by GekidoLukas** [comment]
Hello, I believe MrCrayfish is already working on a 1.20.1 version. I don't know if I want to make it compatible with the fork, because it is not the official release.
However, the idea of example datapacks is very good, and I will take maybe make a few
