### ISSUE TITLE
Suggestion: Entity XP Blacklist Addition

### ISSUE THREAD

**Issue by Z3R0Presence** [GekidoLukas/weaponleveling#59]
I like the mod; it is a great addition to an RPG-style pack of mods. But, I have one somewhat annoying problem: the config does not allow me to list entities that should not grant XP in any way, and I can not figure out how to stop it elsewhere.

The main problem is that the player's weapon can gain experience points by attacking the Dummy (from: https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm). When used responsibly, this is all well and good, but if a player were to, say, AFK autoclick, the player would gain experience points without running the risk of being attacked—the dummy is just a straw attack target, and would also potentially spoil part of the game if i cant remove its ability to power level a weapon.

Therefore, in a manner akin to weapon blacklisting, I would propose adding a configuration for blacklisting entities.

**Comment by GekidoLukas** [comment]
Will be added in 2.2.0
