### ISSUE TITLE
Some Mods that this doesn't work with (1.20.4) FABRIC

### ISSUE THREAD

**Issue by VitaminZeth** [GekidoLukas/weaponleveling#65]
Hello, 

I love and find this mod WONDERFUL. I thought that I would add these mods to the list of incompatible mods:

Chai's Early Game Overhaul: https://www.bing.com/search?q=chais+early+gmae+overhaul&cvid=6e5bbc681916401c908a01beada85e03&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDI5MDBqMGo0qAIIsAIB&FORM=ANAB01&PC=U531

TEAD: https://modrinth.com/mod/tead

WeaponWorks: https://www.curseforge.com/minecraft/mc-mods/weaponworks

Advanced Netherite: https://www.curseforge.com/minecraft/mc-mods/advanced-netherite

**Comment by GekidoLukas** [comment]
The Mod is not released for 1.20.4. Modrinth just showed up as such and I fixed that
