### ISSUE TITLE
Missing Dependency on Modrinth for Fabric 1.20.1

### ISSUE THREAD

**Issue by ZuhaerA** [GekidoLukas/weaponleveling#66]
Just a heads up, I was trying to use the latest version of the fabric mod for 1.20.1 from Modrinth, but the latest two versions don't list "Forge Config API Port" as a dependency, and using the mod without it causes a crash with no mentioning of a missing dependency. The oldest version of the mod for 1.20.1 fabric does however list Forge Config API, and that's how I found out it was needed. Not much of an issue for me, but it might deter other people wanting to try out your mod.

**Comment by GekidoLukas** [comment]
This will be fixed, by removing the need for Forge Config API Port in 2.2.0
