### ISSUE TITLE
Negative durabilty

### ISSUE THREAD

**Issue by ImAGh0st** [GekidoLukas/weaponleveling#67]
Weapons go into negative durability.

E.g: if a leather cap has 32 durability and the player is it for 35 durability the cap will go into -3 durability.

I would really love to use your mod in my pack if there is a way to solve this.

Side note: The clickable discord icon on curse forge is not working.

**Comment by GekidoLukas** [comment]
Fixed in Update 2.2.0

(And thank you, will fix that too :P)
