### ISSUE TITLE
Thrown Trident causes server to crash

### ISSUE THREAD

**Issue by themainvoli** [GekidoLukas/weaponleveling#7]
Drowned thrown trident crashes server (Ticking entity)
[crash-2022-09-25_01.32.57-server.txt](https://github.com/GeradesoLukas/weaponleveling/files/9639973/crash-2022-09-25_01.32.57-server.txt)

Minecraft Version: 1.18.2
Mod Version: weaponleveling-1.18.2-1.2.3.jar

1. Spawn drowned with trident
2. Have it throw the trident at you
3. Crash

**Expected behavior**
The Trident doesn't crash the server.

**Comment by GekidoLukas** [comment]
This is odd, this should be fixed in that version, I will look at it

**Comment by GekidoLukas** [comment]
Okay, I read your crash report, you did not use Version 1.2.3, you used 1.2.2. Please update your mod, this will fix the issue.
