### ISSUE TITLE
old config files not working since 2.2.0

### ISSUE THREAD

**Issue by Fabsian10000** [GekidoLukas/weaponleveling#78]
the new config system introduced in that version of the mod causes the old config files to break, making it impossible to specify any blacklisted items or similar, breaking many things for modpacks in the process.

for me, as i am working on one myself, it has lead to many specifies tools not breaking anymore when they should. and breaking others that shouldnt be breaking

**Comment by GekidoLukas** [comment]
Please read the changelog. You can specify these now in item tags
